CONFIG_CAMPOS = {
    "vencimento_basico":       {"label": "Vencimento Básico (R$)", "tipo": "moeda"},
    "ad_desempenho":    {"label": "Adicional de Desempenho (R$)", "tipo": "moeda"},
    "carga_horaria_mensal":    {"label": "Carga Horária Mensal (h/mês)", "tipo": "hora_mensal"},
    "horas_realizadas": {"label": "Horas Realizadas", "tipo": "horas_realizadas"},
    "ano_referencia":   {"label": "Ano de Referência", "tipo": "ano"},
    "grs_risco": {"label": "GRS", "tipo": "select_risco"},
    "dias_trabalhados": {"label": "Nº de Dias Trabalhados no Mês", "tipo": "dias"},
    "abono_emergencia": {"label": "Abono de Emergência (R$)", "tipo": "moeda"},
    "grat_final_semana": {"label": "Grat. Final de Semana (R$)", "tipo": "moeda"},
    "adicional_noturno": {"label": "Adicional Noturno (R$)", "tipo": "moeda"},
    "numero_meses": {"label": "Nº de Meses de Direito", "tipo": "meses"},
    "valor_giefs": {"label": "Valor da GIEFS (R$)", "tipo": "moeda"},
    "valor_piso": {"label": "Valor do Piso (R$)", "tipo": "moeda"},
}